### ISSUE TITLE
Critical Chance Up

### ISSUE THREAD

**Issue by GlitchMC** [aturfah/eou-skillsim#14]
Medic's Diagnosis and Ronin's crit bonuses are in units of 0.1%, and are additive to the final crit chance, so +300 crit would be +30%, not +200%, etc.

**Comment by aturfah** [comment]
Noted, thank you for this information.

The skill information on the etrianodysseywiki.org was incorrect, and as a result so was the data on the website. I've manually corrected this issue, will issue a PR shortly.
